<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()) : ?>
    <div class="block filter">
        <div class="block-title filter-title">
            <!-- <strong><?= $block->escapeHtml(__('Shop By')) ?></strong> -->
        </div>

        <div class="block-content filter-content">
            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear"><span><?= $block->escapeHtml(__('Clear All')) ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter) : ?>
                <?php if (!$wrapOptions) : ?>
                    <!-- <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= $block->escapeHtml(__('Shopping Options')) ?></strong> -->
                    <dl class="filter-options" id="narrow-by-list">
                    <?php $wrapOptions = true;
                endif; ?>
                    <?php if ($filter->getItemsCount()) : ?>
                        <dt role="heading" aria-level="3" class="filter-options-title" style="font-size:14px;">
                            <?= $block->escapeHtml(__($filter->getName() == 'Category' ? 'Danh mục sản phẩm' : 'Giá')) ?></dt>
                        <dd class="filter-options-content" style=" color: black;line-height: 16px;"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></dd>
                    <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($wrapOptions) : ?>
                    </dl>
                <?php endif; ?>
                <style>
                    .filter {
                        background-color: white;
                        padding: 10px 5px 10px 15px;
                    }

                    .filter-content {
                        padding: 0;
                        margin: 0;
                    }

                    .filter-options-content {
                        font-size: 13px;
                        display: flex;
                    }

                    .items {
                        line-height: 30px;
                    }

                    .count {
                        display: none;
                    }
                </style>
        </div>
    </div>
<?php endif; ?>