<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $escaper \Magento\Framework\Escaper */
/** @var $configProvider \Magento\Search\ViewModel\ConfigProvider */
$configProvider = $block->getData('configProvider');
/** @var $versionManager \Magento\Search\ViewModel\AdditionalSearchFormData */
$additionalSearchFormData = $block->getData('additionalSearchFormData');
/** @var $helper \Magento\Search\Helper\Data */
$helper = $configProvider->getSearchHelperData();
$allowedSuggestion = $configProvider->isSuggestionsAllowed();
$quickSearchUrl = $allowedSuggestion ? $escaper->escapeUrl($helper->getSuggestUrl()) : '';
?>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
<div class="block block-search" style="width:88%;">
    <div class="block block-title"><strong><?= $escaper->escapeHtml(__('Search')) ?></strong></div>
    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form" action="<?= $escaper->escapeUrl($helper->getResultUrl()) ?>" method="get">
            <?php if (!empty($queryParams = $additionalSearchFormData->getFormData())) : ?>
                <?php foreach ($queryParams as $param) : ?>
                    <input type="hidden" name="<?= $escaper->escapeHtmlAttr($param['name']) ?>" value="<?= $escaper->escapeHtmlAttr($param['value']) ?>" />
                <?php endforeach; ?>
            <?php endif; ?>
            <div class="field search">
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?= $escaper->escapeHtml(__('Search')) ?></span>
                </label>
                <div class="control" style="display:inline;">
                    <style>
                        #search {
                            width: 62%;
                            height: 40px;
                            border-radius: 10px;
                            display: inline-block;
                            margin-bottom: 0px;
                        }
                    </style>
                    <input id="search" data-mage-init='{
                            "quickSearch": {
                                "formSelector": "#search_mini_form",
                                "url": "<?= /* @noEscape */ $quickSearchUrl ?>",
                                "destinationSelector": "#search_autocomplete",
                                "minSearchLength": "<?= $escaper->escapeHtml($helper->getMinQueryLength()) ?>"
                            }
                        }' type="text" name="<?= $escaper->escapeHtmlAttr($helper->getQueryParamName()) ?>" value="<?= /* @noEscape */ $helper->getEscapedQueryText() ?>" placeholder="<?= $escaper->escapeHtmlAttr(__('Tiki rẻ mỗi ngày')) ?>" class="input-text" maxlength="<?= $escaper->escapeHtmlAttr($helper->getMaxQueryLength()) ?>" role="combobox" aria-haspopup="false" aria-autocomplete="both" autocomplete="off" aria-expanded="true" />
                    <!-- <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?= $block->getChildHtml() ?>
                </div> -->
                </div>
                <div class="actions" style="display:inline-block;">
                    <button type="submit" title="<?= $escaper->escapeHtml(__('Search')) ?>" class="action search" style="right:400px;" aria-label="Search">
                        <span><?= $escaper->escapeHtml(__('Search')) ?></span>
                    </button>
                </div>
                <div class="links" style="display:inline-block;">
                    <ul>
                        <li style="display:inline; margin-left:0px">
                            <a href="http://nhasachtiki.com/" id="home-page"><i class="bi bi-house-fill"></i>Trang chủ</a>
                        </li>
                        <li class="link authorization-link" data-label="or" style="display:inline; margin-left:16px">
                            <a href="http://nhasachtiki.com/customer/account/login/" id="account"><i class="bi bi-emoji-wink"></i>Tài khoản</a>
                        </li>
                        <li class="link authorization-link" data-label="or" style="display:inline; margin-left:16px">
                            <a href="http://nhasachtiki.com/customer/account/logout/" id="logout"><i class="bi bi-box-arrow-right"></i>Đăng xuất</a>
                        </li>
                    </ul>
                </div>
                <style>
                    .links ul li a:hover {
                        text-decoration: none;
                        background-color: lightgrey;
                        padding: 10px;
                        border-radius: 10px;
                    }

                    .links ul li a {
                        font-size: 16px;
                    }

                    .links ul li a i {
                        margin-right: 5px;
                    }

                    #home-page {
                        color: dodgerblue;
                    }

                    #home-page:hover {
                        background-color: lightblue;
                    }

                    #account,
                    #logout {
                        color: gray;
                    }
                </style>
        </form>
    </div>
</div>
</div>